version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
      tag: '10.9'
    #docker:
    #  - image: node:10-alpine
    steps:
      - checkout
      #- run:
      #    name: Setup image
      #    command: apk add --no-cache ca-certificates --no-progress
      #    working_directory: ./
      # npm config set unsafe-perm true &&
      - node/with-cache:
          cache-key: ./tilde-home-ng/package.json
          dir: ./tilde-home-ng/node_modules
          steps:
            - run:
                name: Install Angular CLI
                command: npm install @angular/cli --save-dev
                working_directory: ./tilde-home-ng
            - run:
                name: NPM Install
                command: npm install
                working_directory: ./tilde-home-ng
      - run:
          name: NPM Build
          command: npx ng build --prod --no-progress
          working_directory: ./tilde-home-ng
      - run:
          name: Copy default 200 handler
          command: cp ./dist/tilde-home-ng/index.html ./dist/tilde-home-ng/200.html
          working_directory: ./tilde-home-ng
      - persist_to_workspace:
          root: ./
          paths:
            - tilde-home-ng
  publish-latest:
    #docker:
    #  - image: node:10-alpine
    executor:
      name: node/default
      tag: '10.9'
    steps:
      #- run:
      #    name: Setup image
      #    command: apk add --no-cache ca-certificates --no-progress
      #    working_directory: ./
      - attach_workspace:
          at: ./
      - run:
          name: Deploy to surge
          working_directory: ./tilde-home-ng
          command: npx surge ./dist/tilde-home-ng tilde.love
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:  # required since `publish-latest` has tag filters AND requires `build`
            tags:
              only: /.*/
      - publish-latest:
          context: tilde-global
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
