version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    #docker:
    #  - image: node:10-alpine
    #working_directory: ~/project/tilde-home-ng
    steps:
      - checkout
      #- run:
      #    name: Setup image
      #    command: apk add --no-cache ca-certificates --no-progress
      #    working_directory: ./
      - node/with-cache:
          working_directory: ~/project/tilde-home-ng
          steps:
            - run:
                name: Install Angular CLI
                command: npm install @angular/cli -g
            - run:
                name: NPM Install
                command: npm install
            - run:
                name: NPM Build
                command: ng build --prod --no-progress
      - run:
          name: Copy default 200 handler
          command: cp ./dist/tilde-home-ng/index.html ./dist/tilde-home-ng/200.html
      - persist_to_workspace:
          root: ~/project/
          paths:
            - tilde-home-ng
  publish-latest:
    #docker:
    #  - image: node:10-alpine
    executor:
      name: node/default
      tag: '10.4'
    steps:
      #- run:
      #    name: Setup image
      #    command: apk add --no-cache ca-certificates --no-progress
      #    working_directory: ./
      - attach_workspace:
          at: ./
      - run:
          name: Deploy to surge
          working_directory: ./tilde-home-ng
          command: ./node_modules/.bin/surge ./dist/tilde-home-ng tilde.love
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:  # required since `publish-latest` has tag filters AND requires `build`
            tags:
              only: /.*/
      - publish-latest:
          context: tilde-global
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
